apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: etaw-knative
  namespace: default
spec:
  revisionTemplate:
    spec:
      container:
        env:
          - name: MESSAGE
            value: BLUE
        image: gcr.io/just-terminus-219317/etaw-knative:latest
